// vue-demo/src/App.vue
<script setup lang="ts">
import { track } from 'nano-custom'
</script>

<template>
  <div class="logos">
    <img src="./assets/vue-logo.svg" alt="Vue Logo" class="logo" width="80" height="80" />
    <img src="https://www.nanosights.dev/images/logo.svg" alt="NanoSights Logo" class="logo" width="80" height="80" />
  </div>
  <h1>Vue + NanoSights</h1>
  <p>This demo shows how NanoSights integrates with Vue.js.</p>
  <div class="buttons">
    <a
      @click="track('CTA')"
      class="button primary"
      href="https://www.nanosights.dev"
      target="_blank">Go to NanoSights</a>
    <a class="button secondary" href="https://www.nanosights.dev/docs">
      Documentation
    </a>
  </div>

  <nano-analytics
    projectKey="mcw2ugsj162ft"
    userId="a5fb0950-8486-43a2-8ee5-dc4f551a4003"
  />
  <nano-insights
    projectKey="mcw2ugsj162ft"
    userId="a5fb0950-8486-43a2-8ee5-dc4f551a4003"
  />
  <nano-custom
    projectKey="mcw2ugsj162ft"
    userId="a5fb0950-8486-43a2-8ee5-dc4f551a4003"
  />
</template>

// angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import 'nano-analytics';
import 'nano-insights';
import { track } from 'nano-custom';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angular-demo';

  // Expose track function as method on component.
  track(eventName: string, eventData?: Record<string, string>) {
    track(eventName, eventData);
  }
}

<div class="logos">
  <img src="angular-logo.gif" alt="Angular Logo" />
  <img src="http://localhost:3000/images/logo.svg" alt="NanoSights Logo" />
</div>
<h1>Angular + NanoSights</h1>
<p>This demo shows how NanoSights integrates with Angular.</p>
<div class="buttons">
  <a
    (click)="track('CTA')"
    class="button primary"
    href="https://www.nanosights.dev"
    target="_blank"
    >Go to NanoSights</a
  >
  <a class="button secondary" href="https://www.nanosights.dev/docs"
    >Documentation</a
  >
</div>

<nano-analytics
  projectKey="mcw2ugsj162ft"
  userId="a5fb0950-8486-43a2-8ee5-dc4f551a4003"
/>

<nano-insights
  projectKey="mcw2ugsj162ft"
  userId="a5fb0950-8486-43a2-8ee5-dc4f551a4003"
/>

<nano-custom
  projectKey="mcw2ugsj162ft"
  userId="a5fb0950-8486-43a2-8ee5-dc4f551a4003"
/>
